export const COMPOUND_CATEGORIES = {
  Testosterone: [
    'Test Cypionate (Test C)',
    'Test Enanthate (Test E)',
    'Test Propionate (Test P)',
    'Testosterone Undecanoate',
    'Sustanon 250',
  ],
  Injectables: [
    'Nandrolone Decanoate (Deca)',
    'Nandrolone Phenylpropionate (NPP)',
    'Boldenone Undecylenate (EQ)',
    'Trenbolone Acetate (Tren A)',
    'Trenbolone Enanthate (Tren E)',
    'Drostanolone Propionate (Mast P)',
    'Drostanolone Enanthate (Mast E)',
    'Primobolan Depot (Primo)',
    'DHB (Dihydroboldenone)',
  ],
  Orals: [
    'Oxandrolone (Anavar)',
    'Oxymetholone (Anadrol)',
    'Methandrostenolone (Dbol)',
    'Stanozolol (Winstrol)',
    'Turinabol (Tbol)',
    'Superdrol',
    'Halotestin',
  ],
  Ancillaries: [
    'Anastrozole (Arimidex)',
    'Exemestane (Aromasin)',
    'Letrozole (Femara)',
    'Tamoxifen (Nolvadex)',
    'Clomiphene (Clomid)',
    'HCG',
    'Cabergoline (Caber)',
    'Pramipexole (Prami)',
    'Raloxifene',
    'TUDCA',
    'NAC',
  ],
  'GLP-1 / Fat Loss': [
    'Semaglutide (Ozempic)',
    'Tirzepatide (Mounjaro)',
    'Retatrutide',
    'Liraglutide (Saxenda)',
    'Tesofensine',
    'BAM15',
    '5-Amino-1MQ',
    'Cagrilintide',
    'Clenbuterol',
    'T3 (Cytomel)',
    'T4 (Synthroid)',
    'DNP',
    'Salbutamol',
    'Yohimbine',
  ],
  Peptides: [
    'BPC-157',
    'TB-500',
    'Ipamorelin',
    'CJC-1295 (no DAC)',
    'CJC-1295 (with DAC)',
    'GHRP-6',
    'GHRP-2',
    'Tesamorelin',
    'PT-141',
    'Melanotan II',
    'GHK-Cu',
    'Thymosin Alpha 1',
    'Kisspeptin',
    'Epithalon',
    'IGF-1 LR3',
  ],
  'Growth Hormone': [
    'Generic GH',
    'Omnitrope',
    'Norditropin',
    'Humatrope',
    'Genotropin',
    'Serostim',
    'MK-677 (Ibutamoren)',
  ],
  Other: ['Custom'],
} as const;

export const ROUTE_OPTIONS = [
  'IM injection',
  'SubQ injection',
  'Oral',
  'Topical',
  'Nasal',
  'Sublingual',
] as const;

export const TRAINING_TYPES = [
  'Push',
  'Pull',
  'Legs',
  'Upper',
  'Lower',
  'Full Body',
  'Biceps',
  'Triceps',
  'Chest',
  'Back',
  'Shoulders',
  'Core',
  'BJJ',
  'Cardio Only',
  'Other',
] as const;

export const DAYS_OF_WEEK = [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
] as const;

export const SLEEP_QUALITY_LABELS: Record<number, string> = {
  1: 'Terrible',
  2: 'Poor',
  3: 'Fair',
  4: 'Good',
  5: 'Excellent',
};

export const MOOD_LABELS: Record<number, string> = {
  1: 'Awful',
  2: 'Bad',
  3: 'Poor',
  4: 'Below Average',
  5: 'Neutral',
  6: 'Decent',
  7: 'Good',
  8: 'Great',
  9: 'Excellent',
  10: 'Amazing',
};
