export type PeptideCategory = 'recomp' | 'fat_loss' | 'longevity' | 'cognitive' | 'sexual_health';

export interface Peptide {
  id: string;
  name: string;
  category: PeptideCategory;
  categoryLabel: string;
  vialSize: string;
  frequency: string;
  headline: string;
  benefits: string[];
  realisticExpectations: {
    week1_2: string;
    week3_4: string;
    week5_8: string;
    week9_plus: string;
    wontFeel: string;
  };
  note?: string;
}

export const CATEGORY_LABELS: Record<PeptideCategory, string> = {
  recomp: 'Recomp Stack',
  fat_loss: 'Fat Loss',
  longevity: 'Longevity',
  cognitive: 'Cognitive',
  sexual_health: 'Sexual Health',
};

export const CATEGORY_FILTERS: { key: PeptideCategory | 'all'; label: string }[] = [
  { key: 'all', label: 'All' },
  { key: 'recomp', label: 'Recomp Stack' },
  { key: 'fat_loss', label: 'Fat Loss' },
  { key: 'longevity', label: 'Longevity' },
  { key: 'cognitive', label: 'Cognitive' },
  { key: 'sexual_health', label: 'Sexual Health' },
];

export const PEPTIDES: Peptide[] = [
  // ── RECOMP STACK ──
  {
    id: 'cjc1295_dac',
    name: 'CJC-1295 with DAC',
    category: 'recomp',
    categoryLabel: 'Recomp Stack',
    vialSize: '10mg vial',
    frequency: '1–2mg weekly SubQ injection',
    headline: 'Long-Acting Growth Hormone Releasing Hormone — The Foundation of GH Optimization',
    benefits: [
      'Stimulates your pituitary gland to produce more of your own growth hormone naturally, restoring youthful GH output that declines ~15% per decade after age 30',
      'The DAC (Drug Affinity Complex) extends the half-life to 8 days, meaning one weekly injection maintains steady elevated GH levels without daily dosing',
      'Accelerates fat metabolism — particularly stubborn visceral and subcutaneous fat — by increasing lipolysis',
      'Enhances deep wave sleep, which is when 75% of your daily growth hormone is released',
      'Supports lean muscle growth and recovery by increasing IGF-1 levels',
      'Improves skin elasticity, collagen production, and overall tissue quality within 4–6 weeks',
      'Strengthens bone density and joint health through increased GH-mediated collagen synthesis',
      'Simple once-weekly injection with consistent, sustained GH elevation',
    ],
    realisticExpectations: {
      week1_2: 'Improved sleep quality, mild water retention as GH levels adjust. Most clients notice deeper sleep within the first week.',
      week3_4: 'Noticeable improvement in recovery between workouts. Skin may start looking fuller. Fat loss begins accelerating if nutrition is dialed.',
      week5_8: 'Visible body composition changes — stubborn fat areas reducing, muscle fullness increasing. Sleep consistently deeper.',
      week9_plus: 'Compounding effects on body composition, skin, hair, nails. Full benefits realized when stacked with training and nutrition protocol.',
      wontFeel: 'This is not a stimulant — you won\'t feel a "rush" or immediate energy boost. GH optimization is a gradual, cumulative process.',
    },
    note: 'Take on an empty stomach (fasted 2+ hours). Best administered before bed to amplify natural nighttime GH pulse.',
  },
  {
    id: 'bpc157',
    name: 'BPC-157',
    category: 'recomp',
    categoryLabel: 'Recomp Stack',
    vialSize: '10mg vial',
    frequency: '250–500mcg daily SubQ',
    headline: 'Body Protection Compound — Accelerated Healing, Gut Repair & Joint Recovery',
    benefits: [
      'Derived from a naturally occurring protective protein in human gastric juice — your body\'s own repair signal, amplified',
      'Dramatically accelerates healing of tendons, ligaments, muscles, and bones — 2–3x faster recovery from soft tissue injuries',
      'Powerful gut-healing properties: repairs intestinal lining, reduces inflammation, reverses damage from NSAIDs, alcohol, and stress',
      'Promotes angiogenesis (new blood vessel formation) at injury sites for faster repair',
      'Protects and heals the GI tract — synergistic with GLP-1 medications that can cause GI side effects',
      'Neuroprotective effects: supports brain healing, reduces anxiety-like behavior, protects dopamine neurons',
      'Anti-inflammatory without the side effects of NSAIDs',
      'Extremely well-tolerated with virtually no reported side effects — one of the safest peptides available',
    ],
    realisticExpectations: {
      week1_2: 'Reduced joint soreness and improved gut comfort. If you have nagging injuries, you\'ll notice less pain during movement.',
      week3_4: 'Significant improvement in chronic aches and pains. Gut issues (bloating, discomfort) noticeably reduced.',
      week5_8: 'Injuries that have lingered for months start resolving. Full gut healing for most clients.',
      week9_plus: 'Near-complete resolution of soft tissue injuries. Can transition to maintenance dosing.',
      wontFeel: 'BPC-157 doesn\'t produce a noticeable "feeling" — it works silently in the background repairing tissue. Judge it by outcomes, not sensation.',
    },
  },
  {
    id: 'tesamorelin',
    name: 'Tesamorelin',
    category: 'recomp',
    categoryLabel: 'Recomp Stack',
    vialSize: '10mg vial',
    frequency: '2mg daily SubQ before bed',
    headline: 'FDA-Approved GHRH Analog — Targeted Visceral Fat Destruction & Lean Body Optimization',
    benefits: [
      'FDA-approved GHRH analog — the only peptide with full FDA approval specifically for reducing visceral adipose tissue',
      'Reduces visceral fat by an average of 18% in clinical trials — the most metabolically dangerous fat',
      'Stimulates natural, pulsatile GH release that mimics your body\'s own rhythm',
      'Significantly reduces liver fat and improves liver enzyme markers (ALT, AST)',
      'Improves body composition without significant changes in diet or exercise alone — amplified with training',
      'Reduces trunk fat while preserving or increasing lean muscle mass',
      'Improves cholesterol profile: reduces triglycerides and LDL while supporting HDL',
      'Enhances cognitive function — improvements in executive function and verbal memory',
    ],
    realisticExpectations: {
      week1_2: 'Improved sleep quality and mild increase in hunger (GH effect). Some clients notice slight water retention.',
      week3_4: 'Midsection starting to feel tighter. Recovery between workouts improving noticeably.',
      week5_8: 'Measurable reduction in waist circumference. InBody scans show visceral fat declining.',
      week9_plus: 'Significant visceral fat reduction. Liver markers improving on blood work. Full recomp effects visible.',
      wontFeel: 'Visceral fat loss happens internally first — you won\'t see dramatic scale changes early, but InBody scans will show the shift.',
    },
  },
  {
    id: 'thymosin_alpha1',
    name: 'Thymosin Alpha-1',
    category: 'recomp',
    categoryLabel: 'Recomp Stack',
    vialSize: '10mg vial',
    frequency: '1.6mg 2x/week SubQ',
    headline: 'Immune System Commander — Deep Immune Modulation & Recovery Enhancement',
    benefits: [
      'Master regulator of immune function — activates dendritic cells, enhances T-cell maturation, modulates immune response',
      'FDA-approved in over 35 countries for hepatitis B/C, immune deficiency, and as a vaccine adjuvant',
      'Modulates and balances the immune response rather than suppressing it — reducing overactivity while strengthening defense',
      'Enhances recovery capacity by reducing systemic inflammation between training sessions',
      'Supports healthy aging — compensates for age-related thymic decline',
      'Anti-tumor properties: enhances natural killer cell activity and cytotoxic T-lymphocyte function',
      'Prevents the immune dip from intense training that leads to illness and missed training days',
      'Twice-weekly dosing for sustained immune optimization with minimal injection burden',
    ],
    realisticExpectations: {
      week1_2: 'Subtle improvements in overall "feeling well." May notice you recover faster from minor bugs.',
      week3_4: 'Training recovery feels more consistent. Less post-workout fatigue and inflammation.',
      week5_8: 'Noticeably fewer sick days. If you typically catch everything going around, you\'ll notice the difference.',
      week9_plus: 'Robust immune function. Blood work may show improved white blood cell markers.',
      wontFeel: 'Immune modulation is background optimization — you won\'t feel a boost, but you\'ll notice the absence of illness and faster recovery.',
    },
  },
  // ── FAT LOSS ──
  {
    id: 'retatrutide',
    name: 'Retatrutide (Reta)',
    category: 'fat_loss',
    categoryLabel: 'Fat Loss',
    vialSize: 'Per vial',
    frequency: 'Weekly SubQ injection',
    headline: 'Triple-Agonist GLP-1 — The Most Advanced Weight Management Compound Available',
    benefits: [
      'Triple receptor agonist (GIP/GLP-1/Glucagon) — activates three metabolic pathways simultaneously',
      'Up to 24% body weight reduction in clinical trials — more than semaglutide or tirzepatide',
      'Specifically targets visceral fat through glucagon receptor activation',
      'Improves insulin sensitivity, reduces HbA1c, and stabilizes fasting glucose',
      'Comprehensive cholesterol improvement: reduces LDL, triglycerides, and total cholesterol',
      'Reduces ALT, AST, and hepatic fat content through glucagon-driven liver fat oxidation',
      'Increases resting metabolic rate — your body burns more calories 24/7, even at rest',
      'Superior appetite regulation compared to single-agonist GLP-1s',
    ],
    realisticExpectations: {
      week1_2: 'Appetite reduction within days. Possible mild nausea as your body adjusts (GI-related, resolves quickly).',
      week3_4: 'Significant appetite control. Early weight loss visible on the scale (mix of water and fat).',
      week5_8: 'Consistent 1–2 lbs/week fat loss. Cravings largely eliminated. Energy levels stabilizing.',
      week9_plus: 'Major body composition changes. Blood markers improving. Clothing fitting noticeably different.',
      wontFeel: 'The triple-agonist mechanism is metabolic, not stimulatory — you won\'t feel "wired." The effect is reduced hunger and steady fat loss.',
    },
    note: 'Discuss with your physician before starting. Insulin or oral diabetes medication dosing may need adjustment.',
  },
  {
    id: 'tesofensine',
    name: 'Tesofensine',
    category: 'fat_loss',
    categoryLabel: 'Fat Loss',
    vialSize: 'Oral capsule',
    frequency: 'Daily oral capsule',
    headline: 'Triple Monoamine Reuptake Inhibitor — Appetite Control, Focus & Metabolic Activation',
    benefits: [
      'Blocks reuptake of serotonin, dopamine, and noradrenaline simultaneously',
      'Clinical trials showed 2x more weight loss than leading GLP-1 drugs',
      'Increases resting metabolic rate by 6–8%',
      'Powerful appetite suppression through a different mechanism than GLP-1 — works centrally (brain) vs. peripherally (gut)',
      'Enhanced dopamine signaling improves motivation, mental clarity, focus, and mood during a deficit',
      'Preserves lean muscle mass during fat loss better than caloric restriction alone',
      'No injections — simple daily oral capsule taken in the morning',
      'Synergistic stacking: Tesofensine (brain) + GLP-1/Reta (gut) = dual-pathway control',
    ],
    realisticExpectations: {
      week1_2: 'Noticeable appetite suppression and improved focus within 3–5 days. Slight increase in heart rate is normal.',
      week3_4: 'Significant reduction in cravings. Mental clarity and motivation noticeably improved. Weight loss accelerating.',
      week5_8: 'Consistent fat loss with muscle preservation. Energy and mood elevated even in a caloric deficit.',
      week9_plus: 'Dramatic body composition changes. Many clients report it\'s the easiest deficit they\'ve ever maintained.',
      wontFeel: 'Some people expect a "stimulant high" — Tesofensine is subtler. The effect is reduced hunger and clearer thinking, not jitteriness.',
    },
    note: 'Start at lowest dose, titrate up over 2 weeks. Monitor heart rate and blood pressure during initiation.',
  },
  {
    id: 'cagrilintide',
    name: 'Cagrilintide',
    category: 'fat_loss',
    categoryLabel: 'Fat Loss',
    vialSize: '10mg vial',
    frequency: 'Weekly SubQ injection',
    headline: 'Long-Acting Amylin Analog — Natural Satiety, Blood Sugar Control & Visceral Fat Loss',
    benefits: [
      'Long-acting amylin receptor agonist — replaces the "forgotten" pancreatic hormone',
      'Up to 15.6% body weight loss when combined with semaglutide (CagriSema) in trials',
      'Produces genuine, natural satiety by activating the brain\'s fullness center',
      'Slows gastric emptying and reduces post-meal glucose spikes',
      'Reduces post-meal glucagon secretion, directly lowering blood sugar',
      'Targets visceral and hepatic fat preferentially',
      'Once-weekly dosing for sustained, consistent appetite control',
      'Especially relevant for Type 1 diabetics who are genuinely amylin-deficient',
    ],
    realisticExpectations: {
      week1_2: 'Feeling fuller faster after meals. Post-meal blood sugar spikes noticeably blunted.',
      week3_4: 'Portion sizes naturally decreasing. Less snacking between meals. Steady early weight loss.',
      week5_8: 'Consistent fat loss, particularly around the midsection. Blood sugar control markedly improved.',
      week9_plus: 'Significant weight loss with preserved lean mass. Blood work showing improved metabolic markers.',
      wontFeel: 'Cagrilintide creates genuine satiety — you simply won\'t want to eat as much. It\'s not forced appetite suppression.',
    },
    note: 'Coordinate with your physician for insulin dose adjustments as blood sugar control improves.',
  },
  // ── LONGEVITY ──
  {
    id: 'motsc',
    name: 'MOTS-c',
    category: 'longevity',
    categoryLabel: 'Longevity',
    vialSize: '40mg vial',
    frequency: '5mg Mon/Wed/Fri SubQ · 4–6 weeks on/off',
    headline: 'Mitochondrial-Derived Peptide — Cellular Energy, Metabolic Activation & Longevity',
    benefits: [
      'Activates AMPK — the master metabolic switch that controls how your cells produce and use energy',
      'Directly improves insulin sensitivity and glucose metabolism by enhancing skeletal muscle glucose uptake',
      'Increases fatty acid oxidation — your body becomes more efficient at using stored fat for energy',
      'Protects against metabolic dysfunction associated with aging, obesity, and sedentary lifestyle',
      'Enhances exercise capacity and endurance by improving mitochondrial function',
      'Anti-aging at the cellular level: preserves telomere length, reduces oxidative stress',
      'Reduces systemic inflammation through AMPK-mediated pathways',
      'Works synergistically with exercise: mimics some molecular benefits of physical activity',
    ],
    realisticExpectations: {
      week1_2: 'Subtle increase in workout endurance. May notice slightly better blood sugar stability after meals.',
      week3_4: 'Improved exercise capacity and recovery. Fat burning during workouts feels more efficient.',
      week5_8: 'Noticeable improvements in body composition and metabolic markers. Energy levels more consistent throughout the day.',
      week9_plus: 'Compounding longevity benefits. Blood work may show improved fasting glucose and inflammatory markers.',
      wontFeel: 'Mitochondrial optimization is invisible — you won\'t "feel" your cells working better, but your performance and recovery will reflect it.',
    },
  },
  {
    id: 'nad',
    name: 'NAD+ Injectable',
    category: 'longevity',
    categoryLabel: 'Longevity',
    vialSize: '1000mg vial',
    frequency: '100–250mg 2–3x/week SubQ',
    headline: 'Cellular Energy Currency — Anti-Aging, Brain Function & Metabolic Restoration',
    benefits: [
      'Required for every energy-producing reaction in every cell — the fuel your mitochondria need',
      'NAD+ levels decline 50% between ages 40–60, causing reduced energy, slower recovery, cognitive decline',
      'Activates sirtuins (SIRT1–SIRT7) — the "longevity genes" that regulate DNA repair and metabolism',
      'Dramatically improves mental clarity, focus, and cognitive performance — many report effects within days',
      'Enhances cellular energy production (ATP) by 30–50%',
      'Supports DNA repair mechanisms critical for preventing cellular damage from training stress and aging',
      'Improves metabolic function: enhances fat oxidation, glucose metabolism, and insulin sensitivity',
      'Injectable form bypasses GI tract for dramatically higher bioavailability than oral NMN/NR supplements',
    ],
    realisticExpectations: {
      week1_2: 'Many clients feel improved mental clarity and energy within the first few days. Sleep quality often improves.',
      week3_4: 'Workout recovery noticeably faster. Sustained energy throughout the day without afternoon crashes.',
      week5_8: 'Cognitive performance consistently elevated. Skin and overall vitality visibly improved.',
      week9_plus: 'Deep cellular restoration. Anti-aging benefits compounding. Blood work may show improved metabolic markers.',
      wontFeel: 'Some people respond quickly, others gradually. If you don\'t feel dramatic changes in week 1, stay the course — cellular repair takes time.',
    },
  },
  {
    id: 'ghkcu',
    name: 'GHK-Cu',
    category: 'longevity',
    categoryLabel: 'Longevity',
    vialSize: '100mg vial',
    frequency: '1–2mg daily SubQ',
    headline: 'Copper Peptide Complex — Tissue Regeneration, Skin Rejuvenation & Anti-Aging',
    benefits: [
      'Naturally occurring copper-binding peptide that declines with age — ~200ng/ml at 20, ~80ng/ml by 60',
      'Activates over 4,000 genes involved in tissue remodeling, switching them toward regeneration',
      'Dramatically stimulates collagen and elastin production — visible skin improvements within 4–8 weeks',
      'Accelerates wound healing and reduces scar formation — 2x faster closure of surgical wounds',
      'Powerful anti-inflammatory: suppresses fibrinogen, TNF-alpha, and other inflammatory markers',
      'Stimulates hair follicle growth and increases hair thickness',
      'Promotes new blood vessel growth for better circulation and tissue oxygenation',
      'Antioxidant properties: protects cells from oxidative damage, UV radiation, and environmental toxins',
    ],
    realisticExpectations: {
      week1_2: 'Subtle improvement in skin hydration and texture. Minor cuts and scrapes may heal slightly faster.',
      week3_4: 'Skin looking visibly smoother and more vibrant. Hair may feel thicker.',
      week5_8: 'Significant skin rejuvenation — clients often get compliments on their skin. Old scars fading.',
      week9_plus: 'Full tissue regeneration benefits. Hair growth improvements visible. Joints and connective tissue stronger.',
      wontFeel: 'GHK-Cu is cosmetic and regenerative — the benefits are visual and structural, not something you "feel" internally.',
    },
  },
  {
    id: 'ss31',
    name: 'SS-31 Elamipretide',
    category: 'longevity',
    categoryLabel: 'Longevity',
    vialSize: '10mg vial',
    frequency: '5mg 3x/week SubQ · 4–6 weeks on/off',
    headline: 'Mitochondrial Targeted Peptide — Cellular Powerhouse Restoration & Organ Protection',
    benefits: [
      'Selectively concentrates in mitochondrial inner membranes and stabilizes the electron transport chain',
      'Restores age-related mitochondrial dysfunction across every organ system',
      'Reduces reactive oxygen species (ROS) production at the source — prevents free radical creation',
      'Improves cardiac function and exercise tolerance — significant improvements in clinical trials',
      'Protects kidney function by stabilizing renal mitochondria',
      'Enhances skeletal muscle performance by improving mitochondrial ATP production',
      'Neuroprotective: preserves brain mitochondrial function for cognitive performance and memory',
      'Currently in FDA clinical trials — one of the most scientifically validated mitochondrial peptides',
    ],
    realisticExpectations: {
      week1_2: 'Subtle improvements in workout endurance and recovery between sets.',
      week3_4: 'Noticeably better exercise tolerance. Cardiovascular capacity feels improved.',
      week5_8: 'Consistent performance improvements. Less fatigue during and after intense training.',
      week9_plus: 'Compounding organ protection and cellular health benefits. Best measured via blood work and performance metrics.',
      wontFeel: 'Mitochondrial repair is a deep cellular process. Benefits show up in your performance numbers and blood work, not as a feeling.',
    },
  },
  // ── COGNITIVE ──
  {
    id: 'selank',
    name: 'Selank',
    category: 'cognitive',
    categoryLabel: 'Cognitive',
    vialSize: '10mg vial',
    frequency: '300–600mcg daily SubQ',
    headline: 'Synthetic Tuftsin Analog — Anxiety Reduction, Cognitive Enhancement & Immune Support',
    benefits: [
      'Reduces anxiety without sedation, addiction potential, or cognitive impairment',
      'Modulates GABA, serotonin, and dopamine simultaneously — creates calm focus',
      'Enhances memory formation, learning speed, and information retention',
      'Stabilizes mood by normalizing BDNF expression — key for neuroplasticity and emotional resilience',
      'Immune-enhancing properties: stimulates natural killer cell activity without immunosuppressive effects',
      'Reduces cortisol and stress hormone response — lowers physiological damage of chronic stress',
      'No tolerance, dependence, or withdrawal — can be used as needed or daily',
      'Subcutaneous injection ensures full bioavailability for consistent, reliable effects',
    ],
    realisticExpectations: {
      week1_2: 'Noticeable reduction in baseline anxiety within days. Feeling calmer under stress without drowsiness.',
      week3_4: 'Improved focus and mental clarity. Stressful situations feel more manageable. Sleep quality improving.',
      week5_8: 'Consistent mood stability. Memory and learning feel sharper. Overall sense of well-being elevated.',
      week9_plus: 'Sustained anxiolytic and cognitive benefits. Many clients reduce or eliminate pharmaceutical anti-anxiety medications (with physician guidance).',
      wontFeel: 'Selank isn\'t a sedative or a "happy pill" — the effect is a subtle but consistent reduction in anxiety and improvement in cognitive clarity.',
    },
  },
  {
    id: 'semax',
    name: 'Semax',
    category: 'cognitive',
    categoryLabel: 'Cognitive',
    vialSize: '10mg vial',
    frequency: '300–600mcg daily SubQ',
    headline: 'Synthetic ACTH Fragment — Nootropic Powerhouse, Neuroplasticity & Mental Performance',
    benefits: [
      'Derived from ACTH 4-10 with enhanced brain penetration and stability',
      'Dramatically increases BDNF — the most important protein for growing new neural connections',
      'Enhances dopamine and serotonin signaling in the prefrontal cortex — better executive function and creativity',
      'Neuroprotective: reduces oxidative damage to neurons, supports recovery from brain injury',
      'Improves attention span and working memory within 30–60 minutes of administration',
      'Synergistic with Selank: Semax handles stimulation/focus, Selank handles calm/anxiety reduction',
      'Supports neurogenesis in the hippocampus — memory formation and spatial reasoning',
      'Subcutaneous injection delivers full systemic bioavailability',
    ],
    realisticExpectations: {
      week1_2: 'Improved focus and mental sharpness within the first dose. Many describe it as "turning the lights on."',
      week3_4: 'Consistent cognitive enhancement. Work output and creative thinking noticeably improved.',
      week5_8: 'Memory and learning capacity measurably better. Complex tasks feel easier to manage.',
      week9_plus: 'Sustained neuroplasticity benefits. When combined with Selank, clients report peak cognitive performance.',
      wontFeel: 'Semax is a nootropic, not a stimulant — the effect is clearer thinking and better focus, not a caffeine-like buzz.',
    },
  },
  // ── SEXUAL HEALTH ──
  {
    id: 'pt141',
    name: 'PT-141 Bremelanotide',
    category: 'sexual_health',
    categoryLabel: 'Sexual Health',
    vialSize: '10mg vial',
    frequency: '1–2mg as needed SubQ · max 8 doses/month',
    headline: 'Melanocortin Receptor Agonist — Sexual Health, Desire & Performance Enhancement',
    benefits: [
      'FDA-approved (as Vyleesi) for hypoactive sexual desire disorder — works on desire at the brain level',
      'Activates MC4R in the hypothalamus — produces genuine desire, not just mechanical function',
      'Works for both men and women — addresses psychological and neurological components of arousal',
      'For men: improves erectile function AND desire simultaneously',
      'For women: clinically proven to increase sexual desire, arousal, and satisfaction',
      'Effects last 24–72 hours from a single dose',
      'Does not interact with the cardiovascular system like PDE5 inhibitors (Viagra, Cialis)',
      'Used as-needed rather than daily — administer 1–2 hours before desired effect',
    ],
    realisticExpectations: {
      week1_2: 'Effects are felt within 1–2 hours of the first dose. Increased desire and arousal are typically immediate.',
      week3_4: 'Optimal dosing dialed in. Understanding your personal response window and ideal timing.',
      week5_8: 'Consistent, reliable enhancement when used as needed. Many clients report improved relationship satisfaction.',
      week9_plus: 'Continued as-needed use. No tolerance buildup — works consistently dose after dose.',
      wontFeel: 'PT-141 creates genuine desire, not forced arousal. If you\'re not in a context that would normally interest you, the effect may be subtle.',
    },
    note: 'May cause temporary nausea and facial flushing. Start with 1mg to assess tolerance. Not for daily use.',
  },
  // ── ADDITIONAL RECOMP ADJACENT ──
  {
    id: 'ipamorelin',
    name: 'Ipamorelin',
    category: 'recomp',
    categoryLabel: 'Recomp Stack',
    vialSize: '10mg vial',
    frequency: '200–300mcg daily SubQ before bed',
    headline: 'Selective GH Secretagogue — Clean Growth Hormone Release Without Side Effects',
    benefits: [
      'One of the most selective GH secretagogues — stimulates GH release without significantly affecting cortisol or prolactin',
      'Produces a strong, predictable GH pulse that mimics natural pulsatile release patterns',
      'Excellent for clients who want GH optimization without the appetite increase of GHRP-6 or hexarelin',
      'Pairs perfectly with CJC-1295 DAC for amplified, sustained GH elevation',
      'Supports fat loss, muscle recovery, and improved sleep quality',
      'Very well-tolerated — one of the mildest GH peptides with minimal side effects',
      'Ideal for GH peptide beginners due to its clean, predictable response',
      'Daily dosing before bed amplifies the natural nighttime GH surge',
    ],
    realisticExpectations: {
      week1_2: 'Improved sleep quality, particularly deeper sleep cycles. Mild hunger increase possible but less than other GH peptides.',
      week3_4: 'Recovery between workouts noticeably improved. Skin and hair quality starting to improve.',
      week5_8: 'Body composition shifting — fat loss accelerating, muscle fullness increasing. Sleep consistently excellent.',
      week9_plus: 'Full GH optimization benefits. Best when stacked with CJC-1295 DAC as part of the recomp protocol.',
      wontFeel: 'Like CJC-1295, this is gradual GH optimization, not an immediate "feel." Track progress with body composition metrics.',
    },
  },
];

export function getPeptideById(id: string): Peptide | undefined {
  return PEPTIDES.find((p) => p.id === id);
}

export function getPeptidesByCategory(category: PeptideCategory): Peptide[] {
  return PEPTIDES.filter((p) => p.category === category);
}
